environment.cpp, environment.h, simulation.cpp, simulation.h, utilities.cpp, utilities.h
Added inputs and optimal output as member variables of environment. 
Added a function to change the inputs by drawing n new values from the environment cue distribution. 
The inputs from the environment can be used in the simulation.
=> Issues #23, #29, #25, #26, #27: dealing with inputs

simulation.cpp
Issue: Simulation can make environment create new inputs to update its own inputs with, based on the number of inputs individuals have
We forgot one yesterday!
=> Added a test for issue #50

environment.cpp, environment.h, simulation.cpp, simulation.h
Issues #46 #47 #48 #49 #50 #52 #54
=> Inputs and outputs are now stored in simulation

environment.cpp, environment.h, observer.cpp, parser.cpp
Issues #57 and #58 have been addressed.
=> Issues #57 and #58

population.cpp, simulation.cpp
I have commented one old test that was no longer relevant (old issue 30) and made issue #68 to replace it as I think what it tested is still something that should be tested for.
=> fixed issue #61

environment.cpp, environment.h, simulation.cpp, simulation.h, utilities.cpp, utilities.h
I have also updated old test 39 so have a look at it.
Do you think the new function for testing function equality is rigorous enough?
=> Fixed issues #62, #71

arc_evo.pro, environment.cpp, network.cpp, network.h, weight.cpp, weight.h
=> Solving issue 85

network.cpp, network.h, simulation.cpp, utilities.cpp, utilities.h
I had to make a few changes to the tests to make everything play nicely, but I think nothing that changes the intention behind them. I'll let you have a look.
=> fixed issues #68 and #73

observer.cpp
```
//#define FIX_ISSUE_81
#ifdef FIX_ISSUE_81
///The observer stores inputs and optimal values
{
observer o;
//Give sim some non-default inputs and optimal
simulation s{};
assign_new_inputs(s);
s.update_optimal(calculate_optimal(s));
assert(o.get_input() != s.get_input());
assert(o.get_optimal() != s.get_optimal());
o.store_input(s);
o.store_optimal(s);
assert(o.get_input() == s.get_input());
assert(o.get_optimal() == s.get_optimal());
}
#endif
```
=> added test for #81

observer.cpp, observer.h, simulation.cpp
=> solved #81

individual.cpp, network.cpp, network.h
I made some (I think) relatively minor changes to test #100 : increased the number of repeats for the test to have some accuracy, added missing arguments to a couple of functions, and changed some names to make them more intuitive (to me). Let me know if I have changed the spirit of the test from what you had in mind, though, it is possible I minsunderstood something.
=> Solved issues #98 and #100

arc_evo.pro, individual.cpp, individual.h, main.cpp, mutation_type.cpp, mutation_type.h, network.cpp, network.h, population.cpp, population.h, simulation.cpp, simulation.h
This is big. 
Check the `enum class` in #108 and check the test for #126. All that is in the middle can be checked in #122 and #123.
=> Issue107 big

observer.cpp, observer.h, simulation.cpp, simulation.h
check issue #105 to know what this is about.
Merge this to #103 if you think this is ok.
=> fixing issue #105

individual.cpp
=> Added test for #120

individual.cpp, individual.h
A test for #125. Let me know if it makes sense, I am working with things I do not wholly understand here.
=> Added test for #125

network.cpp, network.h
=> solved issue #131

individual.cpp, network.cpp, network.h
=> added test for issue #124

main.cpp, observer.cpp, observer.h, simulation.cpp, simulation.h
=> Issue163 164

main.cpp, parser.cpp, parser.h, simulation.cpp, simulation.h
#111 
Let me know if I've misunderstood something about your intentions for this function.
=> solved issue #111

environment.cpp, environment.h, parser.cpp
=> solved issue #143

ScriptNetworkPlot.R
=> updated script to plot networks

individual.h, network.cpp, network.h, observer.cpp, parser.cpp, population.cpp, population.h, simulation.cpp
I added another mutation rate for the activation mutation, if you want to check it over. 
#118 (and #119 ? I didn't really understand what you meant with that one)
=> solved #118

observer.cpp, observer.h
=> trying to template observer smartly

individual.h, main.cpp, network.cpp, network.h, node.cpp, node.h, parser.cpp, population.cpp, population.h, simulation.cpp
=> 202, 199, 203

main.cpp, mutation_type.cpp, mutation_type.h
=> solved #213

parser.cpp
=> solved #215

network.cpp
=> added test for #210. Already solved.

ScriptNetworkPlot.R, mutation_type.cpp, mutation_type.h, network.cpp, network.h, node.h, script_json_arc_evo.R
=> added deletions

arc_evo.pro, get_code_cov.sh
added flags for progiling in release
=> Enable profiling

network.cpp, network.h
I'm not sure what happened, I think some load-bearing parts got deleted during a merge. It should be fixed now.
=> Re-fixed #226

arc_evo.pro, environment.h, ind_data.cpp, ind_data.h, observer.h, simulation.h
=> Save reac norm
